name: For Sale
favicon: null
layout_spectrum: 0.25212
typography_spectrum: 0.74481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#000000'
    - '#c7c7bd'
    - '#999e98'
    - '#5d6162'
  brandStrength: 0.5
  lightness: 0.4047952916007489
  saturation: 0.6973584422376007
  rhythmicContrast: 0.9205629515927285
purpose: []
