name: For Sale
favicon: null
layout_spectrum: 0.25212
typography_spectrum: 0.74481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.20874432404525578
  lightness: 0.4047952916007489
  saturation: 0.6973584422376007
  rhythmicContrast: 0.9205629515927285
purpose: []
